-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 20:40:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flower_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flower_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flower_shop` DEFAULT CHARACTER SET utf8mb4 ;
USE `flower_shop` ;

-- -----------------------------------------------------
-- Table `flower_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `flower_shop`.`trees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`trees` (
  `tree_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `height` DECIMAL(10,2) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`tree_id`),
  UNIQUE INDEX `tree_id_UNIQUE` (`tree_id` ASC) VISIBLE,
  INDEX `fk_trees_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_trees_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `flower_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `flower_shop`.`flowers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`flowers` (
  `flower_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `colour` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`flower_id`),
  UNIQUE INDEX `flower_id_UNIQUE` (`flower_id` ASC) VISIBLE,
  INDEX `fk_flowers_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_flowers_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `flower_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `flower_shop`.`decorations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`decorations` (
  `decoration_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `material` ENUM('wood', 'plastic') NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`decoration_id`),
  UNIQUE INDEX `decoration_id_UNIQUE` (`decoration_id` ASC) VISIBLE,
  INDEX `fk_decorations_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_decorations_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `flower_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `flower_shop`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`sales` (
  `sales_id` INT NOT NULL AUTO_INCREMENT,
  `time_created` TIMESTAMP NOT NULL,
  `total_paid` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sales_id`),
  UNIQUE INDEX `ticket_id_UNIQUE` (`sales_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `flower_shop`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flower_shop`.`sale_items` (
  `sale_items_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  `sales_sales_id` INT NOT NULL,
  PRIMARY KEY (`sale_items_id`),
  UNIQUE INDEX `sale_items_id_UNIQUE` (`sale_items_id` ASC) VISIBLE,
  INDEX `fk_sale_items_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_sale_items_sales1_idx` (`sales_sales_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_items_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `flower_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_items_sales1`
    FOREIGN KEY (`sales_sales_id`)
    REFERENCES `flower_shop`.`sales` (`sales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
